import { MaterialWindow, MaterialWindowAdapter, NavigationDrawer } from "../material-components//material.slint";
import { MainWindowAdapter } from "./main_window_adapter.slint";
import { FilledIcons, OutlinedIcons } from "./icons.slint";
import { SmallAppBar } from "../material-components/ui/components/app_bar.slint";
import { Sidebar } from "./components/sidebar.slint";
import { SpaceView } from "views/space_view.slint";
import { DownloadView, VideoInfo } from "views/download_view.slint";
import { SettingsView } from "views/settings_view.slint";

export component MainWindow inherits MaterialWindow {
    callback get_bili_information(string);
    callback switch_watcher(bool) -> bool;
    private property <bool> settings-enable-watcher;
    private property <string> bvid;
    in property <bool> showInfo;
    in property <string> videoTitle;
    in property <VideoInfo> videoInfo;
    in property <image> inputImage;


    preferred-width: 800px;
    preferred-height: 600px;
    background: MainWindowAdapter.background;
    default-font-family: "Roboto";

    property <int> tab-index;

    HorizontalLayout {
        Sidebar {
            current_item <=> tab-index;
        }
        
        // Switch Tabs
        if tab-index == 0: DownloadView {
            userInput <=> bvid;
            isShowInfo: showInfo;
            videoInfo: videoInfo;
            videoImage: inputImage;

            buttonClicked => {
                // cardName = get_rust_value();
                get_bili_information(bvid);
            }
        }
        if tab-index == 1: SpaceView{}
        if tab-index == 2: SettingsView {
            enable-watcher <=> settings-enable-watcher;
            settingsChanged => {
                switch_watcher(settings-enable-watcher);
            }
        }
    }
}