
import { SmallAppBar } from "../../material-components/material.slint";
import { ScrollView } from "std-widgets.slint";
import { FilledIcons } from "../icons.slint";

// Basic view frame
export component FrameView {
    in property <string> title;
    in property <image> leading-icon;
    callback leading_clicked();
    
    width: 100%;
    height: 100%;
    VerticalLayout {
        HorizontalLayout {
            Rectangle {width: 20px;}
            SmallAppBar {
                title: title;
                leading_button: {
                    icon: leading-icon,
                    enabled: true,
                };
                leading_button_clicked => {leading_clicked()}
            }

        }
        Rectangle {
            background: transparent;
            horizontal-stretch: 1;
            vertical-stretch: 1;

            @children

        }
    }
}

// Scrollable view frame
export component FrameViewScroll {
    in property <string> title;
    in property <image> leading-icon;
    callback leading_clicked();
    width: 100%;
    height: 100%;

    FrameView {
        title: title;
        leading-icon: leading-icon;
        leading_clicked => {leading_clicked()}
        
        HorizontalLayout {
            Rectangle {background: transparent;}
            ScrollView {
                width: 60%;
                @children
            }
            Rectangle {background: transparent;}
        }
    }
}

// VerticalLayout view frame
export component FrameViewVertical {
    in property <string> title;
    in property <image> leading-icon;
    callback leading_clicked();
    width: 100%;
    height: 100%;

    FrameView {
        title: title;
        leading-icon: leading-icon;
        leading_clicked => {leading_clicked()}

        HorizontalLayout {
            Rectangle {background: transparent;}
            VerticalLayout {
                // width: 60%;
                @children
            }
            Rectangle {background: transparent;}
        }
    }
}
