import { NavigationDrawer } from "../../material-components/ui/components/navigation_drawer.slint";
import { FilledIcons, OutlinedIcons } from "../icons.slint";
import { MainWindowAdapter } from "../main_window_adapter.slint";
import { MaterialText } from "../../material-components/ui/components/material_text.slint";

export component Navbar {
    callback selected-tab-changed(int);
    in-out property <int> group_index;
    in-out property <int> item_index;

    width: 250px;
    
    VerticalLayout {
        Rectangle {
            background: #1a1b20;
            padding: 10px;
            
            VerticalLayout {
                padding: 10px;
                MaterialText {
                    text: "FS Manager";
                    font-size: 26px;
                    font-weight: 700;
                    horizontal-alignment: center;
                }
            }
        }
        
        NavigationDrawer {
            current_group: group_index;
            current_item: item_index;
            groups: [
                {
                    title: "Functions",
                    items: [
                        {
                            icon: OutlinedIcons.edit,
                            icon_selected: FilledIcons.edit,
                            text: "Queue",

                        },
                        {
                            icon: OutlinedIcons.bookmark,
                            icon_selected: FilledIcons.bookmark,
                            text: "Library",
                        },
                        {
                            icon: OutlinedIcons.settings,
                            icon_selected: FilledIcons.settings,
                            text: "Settings",
                        }
                    ]
                }
            ];
            changed current_item => {
                selected-tab-changed(self.current_item);
            }
        }
        
    }
    
}