import { NavigationDrawer } from "../../material-components/ui/components/navigation_drawer.slint";
import { FilledIcons, OutlinedIcons } from "../icons.slint";
import { MainWindowAdapter } from "../main_window_adapter.slint";
import { MaterialText } from "../../material-components/ui/components/material_text.slint";

export component Sidebar {
    in-out property <int> current_group;
    in-out property <int> current_item;

    width: 250px;
    
    VerticalLayout {
        Rectangle {
            background: #1a1b20;
            padding: 10px;
            
            VerticalLayout {
                padding: 10px;
                MaterialText {
                    text: "Music-B";
                    font-size: 26px;
                    font-weight: 700;
                    horizontal-alignment: center;
                }
            }
        }
        
        NavigationDrawer {
            current_group <=> current_group;
            current_item <=> current_item;
            groups: [
                {
                    title: "Functions",
                    items: [
                        {
                            icon: OutlinedIcons.archive,
                            icon_selected: FilledIcons.archive,
                            text: "Download",

                        },
                        {
                            icon: OutlinedIcons.account_box,
                            icon_selected: FilledIcons.account_box,
                            text: "Space",
                        },
                        {
                            icon: OutlinedIcons.settings,
                            icon_selected: FilledIcons.settings,
                            text: "Settings",
                        }
                    ]
                }
            ];
        }
        
    }
    
}