import { MaterialText } from "../../material-components/ui/components/material_text.slint";
import { SmallAppBar, FilledButton, Ripple, FilledCard } from "../../material-components/material.slint";
import { ScrollView } from "std-widgets.slint";
import { FrameView, FrameViewVertical } from "../components/frame_view.slint";
import { TextField } from "../../material-components/ui/components/text_field.slint";
import { OutlinedCard } from "../../material-components/ui/components/card.slint";

export component DownloadView {
    in-out property <string> userInput;
    in property <bool> isShowInfo;
    in property <string> VideoTitle;
    callback buttonClicked();

    FrameViewVertical {
        title: "Download";

        // Buttons bar
        VerticalLayout {
            width: 70%;
            spacing: 10px;

            OutlinedCard {
                VerticalLayout {
                    padding: 20px;
                    spacing: 10px;
                    TextField {
                        text <=> userInput;
                        label: "BVID";
                        vertical-stretch: 0;
                    }
                    FilledButton {
                        text: "Submit";
                        vertical-stretch: 0;
                        clicked => {
                            buttonClicked();
                        }
                    }
                }
            }

            if isShowInfo : FilledCard {
                VerticalLayout {
                    padding: 20px;
                    MaterialText {
                        text: "Info";
                        font-size: 18px;
                        font-weight: 650;
                    }
                    MaterialText {
                        text: VideoTitle;
                        font-size: 18px;
                    }
                }
            }
        }
        Rectangle {
            vertical-stretch: 1;
        }
    }
}