import { SmallAppBar, FilledButton, Ripple, FilledCard, Dialog } from "../../material-components/material.slint";
import { ScrollView, ListView, Button } from "std-widgets.slint";
import { FrameView, FrameViewVertical } from "../components/frame_view.slint";
import { FilledIcons } from "../icons.slint";
import { TaskListView } from "download_views/task_list_view.slint";
import { CreateTaskView } from "download_views/create_task_view.slint";

export struct VideoInfo {
    title: string,
    author: string,
    cover: image,
    count: int,
}

export component DownloadView {
    in-out property <string> userInput;
    in property <bool> isShowInfo;
    in property <VideoInfo> videoInfo;
    in property <image> videoImage;
    callback query_info(int, string);
    callback query_finished();

    private property <int> viewIndex: 0;

    if viewIndex == 0 : TaskListView {
        OnCreateTask => {
            viewIndex = 1;
        }
    } // Task List View
    if viewIndex == 1 : CreateTaskView {
        leading_clicked => {
            viewIndex = 0;
        }
        query_info(queryType, input) => {query_info(queryType, input)}
    } // Create List View

}