import { MaterialText } from "../../material-components/ui/components/material_text.slint";
import { SmallAppBar, FilledButton, Ripple, FilledCard } from "../../material-components/material.slint";
import { ScrollView } from "std-widgets.slint";
import { FrameView, FrameViewVertical } from "../components/frame_view.slint";
import { TextField } from "../../material-components/ui/components/text_field.slint";
import { OutlinedCard } from "../../material-components/ui/components/card.slint";

export struct VideoInfo {
    title: string,
    author: string,
    cover: image,
    count: int,
}

export component DownloadView {
    in-out property <string> userInput;
    in property <bool> isShowInfo;
    in property <VideoInfo> videoInfo;
    in property <image> videoImage;
    callback buttonClicked();

    FrameViewVertical {
        title: "Download";

        // Buttons bar
        VerticalLayout {
            width: 70%;
            spacing: 10px;

            FilledCard {
                VerticalLayout {
                    padding: 20px;
                    spacing: 10px;
                    MaterialText {
                        text: "Query";
                        font-size: 18px;
                        font-weight: 700;
                    }
                    TextField {
                        text <=> userInput;
                        label: "BVID";
                        vertical-stretch: 0;
                    }
                    FilledButton {
                        text: "Submit";
                        vertical-stretch: 0;
                        clicked => {
                            buttonClicked();
                        }
                    }
                }
            }

            if true : FilledCard {
                VerticalLayout {
                    Image {
                        source: videoImage;
                    }
                    padding: 20px;
                    MaterialText {
                        text: "Information";
                        font-size: 18px;
                        font-weight: 650;
                    }
                    MaterialText {
                        text: videoInfo.title;
                        font-size: 18px;
                    }
                    MaterialText {
                        text: videoInfo.author;
                        font-size: 18px;
                    }
                    MaterialText {
                        text: videoInfo.count;
                        font-size: 18px;
                    }
                }
            }
        }
        Rectangle {
            vertical-stretch: 1;
        }
    }
}