import { MaterialText } from "../../material-components/ui/components/material_text.slint";
import { SmallAppBar, FilledButton, FilledCard } from "../../material-components/material.slint";
import { ScrollView } from "std-widgets.slint";

export component LibraryView {
    VerticalLayout {
        SmallAppBar {
            title: "Classify Queue";
        }
        
        Rectangle {
            background: transparent;
            horizontal-stretch: 1;
            vertical-stretch: 1;
            
            // Main layout of page
            VerticalLayout {
                horizontal-stretch: 0;
                vertical-stretch: 1;

                // Buttons bar
                HorizontalLayout {
                    horizontal-stretch: 1;
                    padding-left: 20px;
                    padding-right: 30px;
                    padding-top: 10px;
                    spacing: 10px;
                    
                    FilledButton {
                        text: "Button1";
                        horizontal-stretch: 0;
                        vertical-stretch: 0;
                        
                    }
                    FilledButton {
                        text: "Button2";
                        horizontal-stretch: 0;
                        vertical-stretch: 0;
                    }
                    Rectangle {
                        vertical-stretch: 1;
                    }
                }

                // List zone
                HorizontalLayout {
                    padding-top: 20px;
                    // Left list
                    HorizontalLayout {
                        alignment: center;
                        ScrollView {
                            horizontal-stretch: 1;
                            vertical-scrollbar-policy: always-on;

                            width: 220px;
                            
                            VerticalLayout {
                                spacing: 5px;

                                FilledCard {
                                    clickable: true;
                                    Text {
                                        text: "Card1";
                                    }
                                }
                            }
                            

                        }
                    }
                }
            }

        }
    }
}