import { MaterialText } from "../../material-components/ui/components/material_text.slint";
import { SmallAppBar, FilledButton, Ripple, FilledCard } from "../../material-components/material.slint";
import { ScrollView } from "std-widgets.slint";

export component QueueView {
    in property <[string]> cards;
    callback buttonClicked();

    VerticalLayout {
        SmallAppBar {
            title: "Classify Queue";
        }
        
        Rectangle {
            background: transparent;
            horizontal-stretch: 1;
            vertical-stretch: 1;
            
            // Main layout of page
            VerticalLayout {
                horizontal-stretch: 0;
                vertical-stretch: 1;

                // Buttons bar
                HorizontalLayout {
                    horizontal-stretch: 1;
                    padding-left: 20px;
                    padding-right: 30px;
                    padding-top: 10px;
                    spacing: 10px;
                    
                    FilledButton {
                        text: "button1";
                        horizontal-stretch: 0;
                        vertical-stretch: 0;
                        clicked => {buttonClicked()}
                    }
                    FilledButton {
                        text: "Button2";
                        horizontal-stretch: 0;
                        vertical-stretch: 0;
                    }
                    Rectangle {
                        vertical-stretch: 1;
                    }
                }

                HorizontalLayout {
                    padding-top: 20px;
                    alignment: center;
                    // Left list
                    ScrollView {
                        width: 220px;
                        horizontal-stretch: 1;
                        vertical-scrollbar-policy: always-on;
                        
                        VerticalLayout {
                            spacing: 5px;

                            for cardName in cards : FilledCard {
                                height: 60px;
                                width: 200px;

                                MaterialText {
                                    text: cardName;
                                    font-size: 16px;
                                    font-weight: 600;
                                }
                            }
                        }
                    }
                    
                    ScrollView {
                        width: 220px;
                        horizontal-stretch: 1;
                        vertical-scrollbar-policy: always-on;
                        
                        VerticalLayout {
                            spacing: 5px;
                            FilledCard {
                                height: 60px;
                                width: 200px;

                                MaterialText {
                                    text: "SortBox1";
                                    font-size: 16px;
                                    font-weight: 600;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}