import { MaterialText } from "../../material-components/ui/components/material_text.slint";
import { SmallAppBar } from "../../material-components/material.slint";
import { Switch, ScrollView, Button } from "std-widgets.slint";
import { FilledCard } from "../../material-components/ui/components/card.slint";
import { SettingsCard, SettingItem } from "../components/settings_card.slint";
import { FilledButton } from "../../material-components/ui/components/filled_button.slint";
import { FrameView, FrameViewScroll } from "../components/frame_view.slint";
import { FilledIcons } from "../icons.slint";

export component SettingsView {
    in-out property <bool> enable-watcher;
    callback settingsChanged() -> bool;

    FrameViewScroll {
        title: "Settings";
        
        VerticalLayout {
            padding-top: 20px;
            spacing: 20px;

            SettingsCard {
                title: "Functions";
                SettingItem {
                    label: "Folder Watcher";
                    Switch {
                        checked <=> enable-watcher;
                        toggled => {
                            settingsChanged();
                        }
                    }
                }
                SettingItem {
                    label: "Folder Watcher";
                    Switch {
                        checked <=> enable-watcher;
                        toggled => {
                            settingsChanged();
                        }
                    }
                }
            }

            SettingsCard {
                title: "Cache and Data";
                SettingItem {
                    label: "Refresh Wbi";
                    FilledButton {
                        icon: FilledIcons.delete;
                    }
                }
                SettingItem {
                    label: "Clear Cache";
                    FilledButton {
                        icon: FilledIcons.delete;
                    }
                }
            }

            SettingsCard {
                title: "Preview Card";
                SettingItem {
                    label: "Switch Item";
                    Switch {}
                }
                SettingItem {
                    label: "Button Item";
                    FilledButton {text: "button";}
                }
            }

            // Bottom
            Rectangle {
                background: transparent;
                vertical-stretch: 1;
            }
        }
    }
}