import { FilledIcons, OutlinedIcons } from "../../icons.slint";
import { FrameViewVertical } from "../../components/frame_view.slint";
import { FilterChip, TextButton, FloatingActionButton } from "../../../material-components/material.slint";
import { TaskList, ListItem } from "../../components/task_list.slint";


export component CreateTaskEditor {
    // Status
    in-out property <[ListItem]> task_item_list;
    in-out property <bool> is_include_parts;

    width: 100%;
    height: 100%;

    VerticalLayout {
        width: 70%;
        spacing: 10px;

        HorizontalLayout {
            spacing: 10px;

            FilterChip {
                text: @tr("Video Parts");
                height: 30px;
                checked <=> is_include_parts;
            }
            Rectangle {}
        }
        
        TaskList {
            height: 400px;
            items: task_item_list;
        }
    }
}
