import { FilledIcons } from "../../icons.slint";
import { FrameViewVertical } from "../../components/frame_view.slint";
import { MaterialText, FilledCard, TextField, FilledButton, TextButton, FloatingActionButton } from "../../../material-components/material.slint";
import { CreateTaskQuery } from "../../views/download_views/create_task_query.slint";
import { CreateTaskEditor } from "../../views/download_views/create_task_editor.slint";
import { QueryCardInfo } from "../../modules.slint";
import { ListItem } from "../../components/task_list.slint";

struct VideoInfo {
    Title: string,
    Bvid: string,
    Cid: int,
    Cover: image,
    Author: string,
    Count: int,
    Tname: string,
    Publish: int,
    Describe: string,
}

export component CreateTaskView {
    // Status
    in-out property <int> index: 0;

    in-out property <bool> query_is_info_showing;
    in-out property <bool> query_is_querying;
    in-out property <QueryCardInfo> query_card;

    in-out property <bool> is_include_parts: true;
    in-out property <[ListItem]> task_item_list;
    in-out property <bool> is_creating;
    
    callback query_info(int, string);
    callback add_to_temp_list();
    callback add_to_create();
    callback leading_clicked(); // back button
    callback back_to_query();

    width: 100%;
    height: 100%;

    FrameViewVertical {
        title: "Create Download Task";
        leading-icon: FilledIcons.arrow_back;
        leading_clicked => {leading_clicked()}

        if index == 1 : HorizontalLayout {
            padding-left: 15px;
            TextButton {
                text: "Cancel";
                icon: FilledIcons.undo;
                clicked => {back_to_query()}
            }
            Rectangle {}
        }

        if index == 0 : CreateTaskQuery {
            is_info_showing <=> query_is_info_showing;
            is_querying <=> query_is_querying;
            query_card_info: query_card;
            query_info(queryType, input) => {query_info(queryType, input)}
            add_to_temp_list => {add_to_temp_list()}
        }
        if index == 1 : CreateTaskEditor {
            task_item_list: root.task_item_list;
            is_include_parts <=> root.is_include_parts;
        }
        
        Rectangle {}
    }
    
    // Create task button
    if index == 1 && !is_creating : FloatingActionButton {
        text: "Create";
        icon: FilledIcons.add;
        style: standard;
        x: parent.width - self.width - 16px;
        y: parent.height - self.height - 16px;
        clicked => {add_to_create()}
    }

}
