import { FilledIcons } from "../../icons.slint";
import { FrameViewVertical } from "../../components/frame_view.slint";
import { MaterialText, FilledCard, SegmentedButton, TextField, FilledButton } from "../../../material-components/material.slint";
import { QueryCardInfo } from "../../modules.slint";

// struct VideoInfo {
//     Title: string,
//     Bvid: string,
//     Cid: int,
//     Cover: image,
//     Author: string,
//     Count: int,
//     Tname: string,
//     Publish: int,
//     Describe: string,
// }

// The label for info card
component Label {
    in property <string> label;
    in property <string> value;
    HorizontalLayout {
        spacing: 5px;
        MaterialText {
            text: label;
            font-weight: 600;
        }
        MaterialText {text: value;}
        Rectangle {}
    }
}

export component CreateTaskQuery {
    // Status
    in-out property <bool> is_info_showing;
    in-out property <bool> is_querying;
    in-out property <QueryCardInfo> query_card_info;
    private property <int> queryType;
    private property <string> userInput;
    
    callback query_info(int, string);
    callback add_to_temp_list();
    callback leading_clicked(); // back button

    VerticalLayout {
        spacing: 10px;
        FilledCard {
            width: 60%;
            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                // Card title
                MaterialText { text: @tr("Query"); font-size: 18px; font-weight: 600; }
                HorizontalLayout {
                    SegmentedButton {
                        items: [
                            {text: @tr("BVID"),},
                            {text: @tr("Collect"),},
                        ];
                        current_index <=> queryType;
                    }
                    Rectangle {}
                }
                TextField {
                    text <=> userInput;
                    label: @tr("Please input ID");
                    vertical-stretch: 0;
                }
                FilledButton {
                    text: @tr("Query");
                    vertical-stretch: 0;
                    icon: FilledIcons.search;
                    enabled: !is_querying;
                    
                    clicked => {
                        is_querying = true;
                        query_info(queryType, userInput);
                    }
                }
            }
        }

        // Infomation card
        if is_info_showing : FilledCard {
            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                MaterialText {
                    text: @tr("Information");
                    font-size: 18px;
                    font-weight: 650;
                }
                HorizontalLayout {
                    Image {
                        width: 40%;
                        
                        source: query_card_info.cover;
                    }
                    Rectangle {}
                    VerticalLayout {
                        Label {
                            label: @tr("Title");
                            value: query_card_info.title;
                        }
                        Label {
                            label: @tr("Author");
                            value: query_card_info.author;
                        }
                        Label {
                            label: @tr("Count");
                            value: query_card_info.count;
                        }
                    }
                }

                FilledButton {
                    text: @tr("Confirm");
                    icon: FilledIcons.add;
                    clicked => {add_to_temp_list()}
                }
            }
            // CircularProgressIndicator {
            //     indeterminate: true;
            //     value: 0.3;
            // }
        }
    }
}
